### ISSUE TITLE
Cannot import on Python 3.8

### ISSUE THREAD

**Issue by tfburns** [trivicious/gillespie#1]
Using Windows 10 Anaconda environment with Python 3.8.12.

After installing via pip, I see the following in the list after I type `conda list` in the Anaconda prompt:
```
gillespie                 0.0.1                    pypi_0    pypi
```

But, when I try `import gillespie`, I get:
```
Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gillespie
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gillespie'
>>>
```

I can, however, use `git clone https://github.com/sueskind/gillespie.git` followed by `python setup.py install` and then, within that directory do `import src as gillespie` and I can run the example in the current readme.

**Comment by sueskind** [comment]
Are you sure that you installed it to the correct environment? Have you tried using a [venv](https://docs.python.org/3/library/venv.html)?

**Comment by tfburns** [comment]
Just double checked and repeated the same as above. I haven't and probably won't try venv.

For now, I'm just copy & pasting the `simulate` function from `src/_gillespie.py` into my working code.

**Comment by sueskind** [comment]
Sorry for not responding for this long. I would like to reproduce your issue, could you tell me exactly what commands/actions you did, starting from a fresh dummy project?
