### ISSUE TITLE
Usage of Gillespie module from cloned repository

### ISSUE THREAD

**Issue by marcoxa** [trivicious/gillespie#3]
Hi

can you please give an example or two about how to use the system from a cloned, non pip installed, repository?  Possibly both form the CLI and from the Python REPL?

Thanks

Marco

**Comment by sueskind** [comment]
I documented how to run the examples when cloning the project from the command-line in the project's README (see the commit).

Of course, you can also run the examples outside of this project (i.e. without cloning it) when installing `gillespie` via pip. Then the `import src as gillespie` in a given example must be changed to `import gillespie`.

Running an example from the REPL boils down to installing `gillespie` via pip and entering the example's code line-by-line.

Does this answer your question?

**Comment by marcoxa** [comment]
Thank you... That helps.

All the best

Marco

PS I am showing your code to my students as an example of how such a piece of software should be (1) conceived and (2) written.  Very elegant and concise.

**Comment by sueskind** [comment]
Thank you for your support!
